name: brain_monitor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.3.1
  fl_chart: 0.50.1
  retrofit: 3.0.1+1
  logger: 1.1.0
  freezed_annotation: 2.0.1
  dio: 4.0.6
  image_picker: 0.8.5
  image_picker_for_web: 2.1.6
  image_picker_web: 2.1.1
  file_picker: 4.5.1
  percent_indicator: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: 2.1.10
  freezed: 2.0.2
  lint: ^1.6.0
  retrofit_generator: 4.0.1
  json_serializable: 6.1.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

